// Code generated by gengo:runtimedoc DO NOT EDIT.
package v2

func (v *CatalogResponse) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Repositories":
			return []string{
				"仓库列表",
			}, true
		}

		return nil, false
	}
	return []string{}, true
}

func (*Digest) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"内容摘要",
	}, true
}

func (v *ErrBlobInvalidDigest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Digest":
			return []string{
				"期望的摘要",
			}, true
		case "Reason":
			return []string{
				"不匹配的原因",
			}, true

		}

		return nil, false
	}
	return []string{
		"Blob 摘要不匹配",
	}, true
}

func (v *ErrBlobInvalidLength) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Reason":
			return []string{
				"不匹配的原因",
			}, true
		}

		return nil, false
	}
	return []string{
		"Blob 长度不匹配",
	}, true
}

func (v *ErrBlobUnknown) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Digest":
			return []string{
				"Blob 摘要",
			}, true
		}

		return nil, false
	}
	return []string{
		"Blob 不存在",
	}, true
}

func (v *ErrBlobUploadUnknown) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}

		return nil, false
	}
	return []string{
		"分块上传不存在",
	}, true
}

func (v *ErrManifestBlobUnknown) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"仓库名称",
			}, true
		case "Digest":
			return []string{
				"Blob 摘要",
			}, true

		}

		return nil, false
	}
	return []string{
		"清单引用的 Blob 不存在",
	}, true
}

func (v *ErrManifestNameInvalid) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"仓库名称",
			}, true
		case "Reason":
			return []string{
				"无效的原因",
			}, true

		}

		return nil, false
	}
	return []string{
		"清单名称无效",
	}, true
}

func (v *ErrManifestUnknownRevision) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"仓库名称",
			}, true
		case "Revision":
			return []string{
				"清单摘要",
			}, true

		}

		return nil, false
	}
	return []string{
		"清单修订版本不存在",
	}, true
}

func (v *ErrManifestUnverified) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}

		return nil, false
	}
	return []string{
		"清单校验失败",
	}, true
}

func (v *ErrNotImplemented) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Reason":
			return []string{
				"未实现的原因",
			}, true
		}

		return nil, false
	}
	return []string{
		"操作未实现",
	}, true
}

func (v *ErrRepositoryNameInvalid) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"仓库名称",
			}, true
		case "Reason":
			return []string{
				"无效的原因",
			}, true

		}

		return nil, false
	}
	return []string{
		"仓库名称无效",
	}, true
}

func (v *ErrRepositoryUnknown) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"仓库名称",
			}, true
		}

		return nil, false
	}
	return []string{
		"仓库不存在",
	}, true
}

func (v *ErrTagUnknown) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"仓库名称",
			}, true
		case "Tag":
			return []string{
				"标签名",
			}, true

		}

		return nil, false
	}
	return []string{
		"标签不存在",
	}, true
}

func (*Name) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"仓库名称",
	}, true
}

func (v *Range) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Start":
			return []string{
				"起始位置",
			}, true
		case "Length":
			return []string{
				"长度",
			}, true

		}

		return nil, false
	}
	return []string{
		"字节范围，用于分块上传的 Content-Range 头",
	}, true
}

func (*Reference) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"清单引用，可以是 Tag 或 Digest",
	}, true
}

func (v *TagList) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"仓库名称",
			}, true
		case "Tags":
			return []string{
				"标签列表",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
