[group('meta')]
default:
    @just --list

[group('release')]
[no-cd]
publish:
    dagger call container \
        push \
            --registry "ghcr.io" \
            --username ${GH_USERNAME} \
            --password env://GH_PASSWORD

[group('dev')]
[no-cd]
serve:
    dagger call service up

[no-cd]
update:
    dagger update
