
export CGO_ENABLED := "0"

crkit := "go tool crkit"

# 列出所有可用命令
[group('meta')]
default:
    @just --list

# 启动本地 registry 服务
[group('dev')]
[no-cd]
serve-registry:
    {{ crkit }} serve registry -c \
    	--log-format=text \
    	--addr=:5070

# 启动本地 registry 服务
[group('dev')]
[no-cd]
serve-registry-deploy-preset:
    {{ crkit }} serve registry --deploy-preset

# 垃圾回收（干运行）
[group('dev')]
[no-cd]
gc:
    {{ crkit }} gc -c --log-level=debug --dry-run

# 代理模式启动
[group('dev')]
[no-cd]
serve-registry-with-proxy:
    {{ crkit }} serve registry -c \
    	--log-format=text \
    	--remote-endpoint=https://${CONTAINER_REGISTRY} \
    	--remote-username=${CONTAINER_REGISTRY_USERNAME} \
    	--remote-password=${CONTAINER_REGISTRY_PASSWORD} \
    	--addr=:5070

[group('release')]
[no-cd]
artifact $GOOS=`go env GOOS` $GOARCH=`go env GOARCH` *args='-o=target/${GOOS}-${GOARCH}/crkit':
    go build \
        {{ args }} \
        -ldflags='-s -w -X github.com/octohelm/crkit/internal/version.version={{ env("VERSION", "devel") }}' \
        {{ module_directory() }}
