/*
Package api GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package api

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v NamespaceProvider) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Remote":
			return []string{}, true
		case "Content":
			return []string{}, true
		case "Namespace":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Namespace, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}
