/*
Package api GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package api

import (
	context "context"

	content "github.com/octohelm/crkit/pkg/content"
	fsdriver "github.com/octohelm/crkit/pkg/content/fs/driver"
)

func (p *NamespaceProvider) InjectContext(ctx context.Context) context.Context {
	ctx = p.Content.InjectContext(ctx)
	ctx = fsdriver.DriverInjectContext(ctx, p.driver)
	ctx = content.NamespaceInjectContext(ctx, p.namespace)

	return ctx
}

func (v *NamespaceProvider) Init(ctx context.Context) error {
	if err := v.beforeInit(ctx); err != nil {
		return err
	}
	if err := v.Content.Init(ctx); err != nil {
		return err
	}

	if err := v.afterInit(ctx); err != nil {
		return err
	}

	return nil
}
