/*
Package remote GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package remote

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v RegistryConfig) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{
				"Remote container registry endpoint",
			}, true
		case "Username":
			return []string{
				"Remote container registry username",
			}, true
		case "Password":
			return []string{
				"Remote container registry password",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
