// Code generated by gengo:injectable DO NOT EDIT.
package registry

import (
	context "context"
	fmt "fmt"

	content "github.com/octohelm/crkit/pkg/content"
)

func (v *CancelBlobUpload) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *Catalog) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *CreateBlobUpload) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *DeleteBlob) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *DeleteManifest) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *GetBlob) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *GetBlobUpload) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *GetManifest) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *HeadBlob) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *HeadManifest) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *ListTag) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *PatchBlobUpload) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *PutBlobUpload) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *PutManifest) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}
