// Code generated by gengo:injectable DO NOT EDIT.
package registry

import (
	context "context"
	fmt "fmt"

	content "github.com/octohelm/crkit/pkg/content"
)

func (v *CancelBlobUpload) Init(ctx context.Context) error {
	if err := v.NameScoped.Init(ctx); err != nil {
		return err
	}

	return nil
}

func (v *Catalog) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *CreateBlobUpload) Init(ctx context.Context) error {
	if err := v.NameScoped.Init(ctx); err != nil {
		return err
	}

	return nil
}

func (v *GetBlobUpload) Init(ctx context.Context) error {
	if err := v.NameScoped.Init(ctx); err != nil {
		return err
	}

	return nil
}

func (v *NameScoped) Init(ctx context.Context) error {
	if value, ok := content.NamespaceFromContext(ctx); ok {
		v.namespace = value
	} else {
		return fmt.Errorf("missing provider %T.namespace", v)
	}

	return nil
}

func (v *PatchBlobUpload) Init(ctx context.Context) error {
	if err := v.NameScoped.Init(ctx); err != nil {
		return err
	}

	return nil
}

func (v *PutBlobUpload) Init(ctx context.Context) error {
	if err := v.NameScoped.Init(ctx); err != nil {
		return err
	}

	return nil
}
