// Code generated by gengo:operator DO NOT EDIT.
package registry

import (
	io "io"

	courier "github.com/octohelm/courier/pkg/courier"

	manifestv1 "github.com/octohelm/crkit/pkg/apis/manifest/v1"
	registryv2 "github.com/octohelm/crkit/pkg/apis/registry/v2"
)

func init() {
	R.Register(courier.NewRouter(&BaseURL{}))
}

func (BaseURL) ResponseContent() any {
	return new(map[string]string)
}

func init() {
	R.Register(courier.NewRouter(&CancelBlobUpload{}))
}

func (CancelBlobUpload) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&Catalog{}))
}

func (Catalog) ResponseContent() any {
	return new(registryv2.CatalogResponse)
}

func init() {
	R.Register(courier.NewRouter(&CreateBlobUpload{}))
}

func (CreateBlobUpload) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&DeleteBlob{}))
}

func (DeleteBlob) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&DeleteManifest{}))
}

func (DeleteManifest) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&GetBlob{}))
}

func (GetBlob) ResponseContent() any {
	return new(io.ReadCloser)
}

func init() {
	R.Register(courier.NewRouter(&GetBlobUpload{}))
}

func (GetBlobUpload) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&GetManifest{}))
}

func (GetManifest) ResponseContent() any {
	return new(manifestv1.Payload)
}

func init() {
	R.Register(courier.NewRouter(&HeadBlob{}))
}

func (HeadBlob) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&HeadManifest{}))
}

func (HeadManifest) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&ListTag{}))
}

func (ListTag) ResponseContent() any {
	return new(registryv2.TagList)
}

func init() {
	R.Register(courier.NewRouter(&PatchBlobUpload{}))
}

func (PatchBlobUpload) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&PutBlobUpload{}))
}

func (PutBlobUpload) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&PutManifest{}))
}

func (PutManifest) ResponseContent() any {
	return nil
}
