/*
Package registry GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package registry

import (
	io "io"

	courier "github.com/octohelm/courier/pkg/courier"
	manifestv1 "github.com/octohelm/crkit/pkg/apis/manifest/v1"
	content "github.com/octohelm/crkit/pkg/content"
)

func init() {
	R.Register(courier.NewRouter(&BaseURL{}))
}

func (*BaseURL) ResponseContent() any {
	return new(map[string]string)
}

func (*BaseURL) ResponseData() *map[string]string {
	return new(map[string]string)
}

func init() {
	R.Register(courier.NewRouter(&CancelUploadBlob{}))
}

func (*CancelUploadBlob) ResponseContent() any {
	return nil
}

func (*CancelUploadBlob) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}

func init() {
	R.Register(courier.NewRouter(&DeleteBlob{}))
}

func (*DeleteBlob) ResponseContent() any {
	return nil
}

func (*DeleteBlob) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}

func init() {
	R.Register(courier.NewRouter(&DeleteManifest{}))
}

func (*DeleteManifest) ResponseContent() any {
	return nil
}

func (*DeleteManifest) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}

func init() {
	R.Register(courier.NewRouter(&GetBlob{}))
}

func (*GetBlob) ResponseContent() any {
	return new(io.ReadCloser)
}

func (*GetBlob) ResponseData() *io.ReadCloser {
	return new(io.ReadCloser)
}

func init() {
	R.Register(courier.NewRouter(&GetManifest{}))
}

func (*GetManifest) ResponseContent() any {
	return new(manifestv1.Payload)
}

func (*GetManifest) ResponseData() *manifestv1.Payload {
	return new(manifestv1.Payload)
}

func init() {
	R.Register(courier.NewRouter(&HeadBlob{}))
}

func (*HeadBlob) ResponseContent() any {
	return new(any)
}

func (*HeadBlob) ResponseData() *any {
	return new(any)
}

func init() {
	R.Register(courier.NewRouter(&HeadManifest{}))
}

func (*HeadManifest) ResponseContent() any {
	return new(any)
}

func (*HeadManifest) ResponseData() *any {
	return new(any)
}

func init() {
	R.Register(courier.NewRouter(&ListTag{}))
}

func (*ListTag) ResponseContent() any {
	return new(content.TagList)
}

func (*ListTag) ResponseData() *content.TagList {
	return new(content.TagList)
}

func init() {
	R.Register(courier.NewRouter(&PutManifest{}))
}

func (*PutManifest) ResponseContent() any {
	return new(any)
}

func (*PutManifest) ResponseData() *any {
	return new(any)
}

func init() {
	R.Register(courier.NewRouter(&UploadBlob{}))
}

func (*UploadBlob) ResponseContent() any {
	return new(any)
}

func (*UploadBlob) ResponseData() *any {
	return new(any)
}

func init() {
	R.Register(courier.NewRouter(&UploadPatchBlob{}))
}

func (*UploadPatchBlob) ResponseContent() any {
	return new(any)
}

func (*UploadPatchBlob) ResponseData() *any {
	return new(any)
}

func init() {
	R.Register(courier.NewRouter(&UploadPutBlob{}))
}

func (*UploadPutBlob) ResponseContent() any {
	return new(any)
}

func (*UploadPutBlob) ResponseData() *any {
	return new(any)
}
