// Code generated by gengo:injectable DO NOT EDIT.
package registryhttp

import (
	context "context"
)

func (v *Server) Init(ctx context.Context) error {
	if err := v.beforeInit(ctx); err != nil {
		return err
	}
	if err := v.Server.Init(ctx); err != nil {
		return err
	}

	return nil
}
