// Code generated by gengo:runtimedoc DO NOT EDIT.
package remote

func (v *Client) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "RoundTripperCreateFunc":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.Registry, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (*Option) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (v *Registry) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{
				"Remote container registry endpoint",
			}, true
		case "Username":
			return []string{
				"Remote container registry username",
			}, true
		case "Password":
			return []string{
				"Remote container registry password",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *RegistryAuth) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Username":
			return []string{}, true
		case "Password":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *RegistryClient) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ClientCertificateData":
			return []string{
				"https cert (pem-encoded)",
			}, true
		case "ClientKeyData":
			return []string{
				"https key (pem-encoded)",
			}, true
		case "SkipVerify":
			return []string{
				"https skip",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *RegistryHost) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Server":
			return []string{}, true
		case "Auth":
			return []string{}, true
		case "CertificateAuthorityData":
			return []string{}, true
		case "Client":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (*RegistryHosts) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
