/*
Package remote GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package remote

import _ "embed"

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *Client) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "RoundTripperCreateFunc":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.Registry, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (*Option) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (v *Registry) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{
				"Remote container registry endpoint",
			}, true
		case "Username":
			return []string{
				"Remote container registry username",
			}, true
		case "Password":
			return []string{
				"Remote container registry password",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
