/*
Package registry GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package registry

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (BaseHost) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (v Cleaner) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Job":
			return []string{}, true
		case "UntagWhenNotExistsInKube":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Job, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v Configuration) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "StorageRoot":
			return []string{}, true
		case "RegistryAddr":
			return []string{}, true
		case "RegistryBaseHost":
			return []string{}, true
		case "Proxy":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Publisher) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "PublicIP":
			return []string{}, true
		case "Namespace":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Server) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Storage":
			return []string{}, true
		case "RemoteRegistry":
			return []string{}, true
		case "Addr":
			return []string{
				"The address the server endpoint binds to",
			}, true
		case "Cleaner":
			return []string{}, true
		case "Publisher":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Publisher, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v Storage) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Root":
			return []string{
				"Storage dir root",
			}, true
		}

		return nil, false
	}
	return []string{}, true
}
