/*
Package authn GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package authn

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v Authn) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CheckEndpoint":
			return []string{}, true
		case "ClientID":
			return []string{}, true
		case "ClientSecret":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v ErrUnauthorized) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Reason":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Token) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "TokenType":
			return []string{}, true
		case "ExpiresIn":
			return []string{}, true
		case "AccessToken":
			return []string{}, true
		case "RefreshToken":
			return []string{}, true
		case "Scope":
			return []string{}, true
		case "ExpiredAt":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v WwwAuthenticate) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AuthType":
			return []string{}, true
		case "Params":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
