// Code generated by gengo:runtimedoc DO NOT EDIT.
package v2

func (v *BaseURL) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}

		return nil, false
	}
	return []string{
		"注册中心根路径",
	}, true
}

func (v *CancelBlobUpload) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "ID":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"取消分块上传",
	}, true
}

func (v *Catalog) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}

		return nil, false
	}
	return []string{
		"列出仓库",
	}, true
}

func (v *CreateBlobUpload) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "ContentLength":
			return []string{}, true
		case "ContentType":
			return []string{}, true
		case "Digest":
			return []string{}, true
		case "Blob":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"创建分块上传",
	}, true
}

func (v *DeleteBlob) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Digest":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"删除 Blob",
	}, true
}

func (v *DeleteManifest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Reference":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"删除清单",
	}, true
}

func (v *GetBlob) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Digest":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"下载 Blob",
	}, true
}

func (v *GetBlobUpload) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "ID":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"查询分块上传状态",
	}, true
}

func (v *GetManifest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Accept":
			return []string{}, true
		case "Reference":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"获取清单",
	}, true
}

func (v *HeadBlob) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Digest":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"检查 Blob 是否存在",
	}, true
}

func (v *HeadManifest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Accept":
			return []string{}, true
		case "Reference":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"检查清单是否存在",
	}, true
}

func (v *ListTag) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		}

		return nil, false
	}
	return []string{
		"列出标签",
	}, true
}

func (v *PatchBlobUpload) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "ID":
			return []string{}, true
		case "Chunk":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"上传分块数据",
	}, true
}

func (v *PutBlobUpload) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "ID":
			return []string{}, true
		case "ContentRange":
			return []string{}, true
		case "ContentLength":
			return []string{}, true
		case "Digest":
			return []string{}, true
		case "Chunk":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"完成分块上传",
	}, true
}

func (v *PutManifest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Reference":
			return []string{}, true
		case "Manifest":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"推送清单",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
