/*
Package driver GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package driver

import (
	context "context"
)

type contextDriver struct{}

func DriverFromContext(ctx context.Context) (Driver, bool) {
	if v, ok := ctx.Value(contextDriver{}).(Driver); ok {
		return v, true
	}
	return nil, false
}

func DriverInjectContext(ctx context.Context, tpe Driver) context.Context {
	return context.WithValue(ctx, contextDriver{}, tpe)
}
