/*
Package uploadpurger GENERATED BY gengo:injectable
DON'T EDIT THIS FILE
*/
package uploadpurger

import (
	context "context"

	fsdriver "github.com/octohelm/crkit/pkg/content/fs/driver"
)

func (v *UploadPurger) Init(ctx context.Context) error {
	if value, ok := fsdriver.DriverFromContext(ctx); ok {
		v.driver = value
	}
	if err := v.Agent.Init(ctx); err != nil {
		return err
	}

	if err := v.afterInit(ctx); err != nil {
		return err
	}

	return nil
}
