// Code generated by gengo:injectable DO NOT EDIT.
package uploadpurger

import (
	context "context"

	pkgdriver "github.com/octohelm/crkit/pkg/driver"
)

func (v *UploadPurger) Init(ctx context.Context) error {
	if value, ok := pkgdriver.DriverFromContext(ctx); ok {
		v.driver = value
	}
	if err := v.Agent.Init(ctx); err != nil {
		return err
	}

	if err := v.afterInit(ctx); err != nil {
		return err
	}

	return nil
}
