name: ci

on:
  push:
    branches:
      - "*"
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GH_USERNAME: ${{ github.actor }}
      GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v3
      - uses: docker/setup-qemu-action@v2
      - run: curl -sSLf https://raw.githubusercontent.com/octohelm/piper/main/install.sh | sudo sh

      - run: just ship
