name: ci

on:
  push:
    branches:
      - "*"
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        target: [ ship, archive ]

    runs-on: ubuntu-latest

    env:
      GH_USERNAME: ${{ github.actor }}
      GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v2
      - run: curl -sSLf https://raw.githubusercontent.com/octohelm/wagon/main/install.sh | sudo sh

      - run: make ship

      - if: ${{ matrix.target == 'archive' || github.ref == 'refs/heads/main' }}
        run: make archive

      - if: ${{ matrix.target == 'archive' && github.ref == 'refs/heads/main' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            .wagon/build/*.tar.gz
